services:
    sync_job:
        image: docsoc/clickup-calendar-sync
        build:
            context: ../.. # We need the monorepo root as deps are managed and built to the root
            dockerfile: ./packages/docsoc_clickup_calendar_sync/Dockerfile
        init: true # don't run as PID 1 so we can kill the sleep process
        # Run every 30 mins
        command: ["./scripts/run_interval.sh", "/usr/local/bin/docsoc_clickup_calendar_sync", "30m"]
        depends_on:
            - postgres
        environment:
            # The following environment variables should be set in the .env file
            # and docker compose will auto load them
            DATABASE_URL: postgresql://docsoc:docsoc@postgres/docsoc
            ICAL_SYNC_PRIVATE_ICAL: ${ICAL_SYNC_PRIVATE_ICAL}
            ICAL_SYNC_START_DATE: ${ICAL_SYNC_START_DATE}
            ICAL_SYNC_END_DATE: ${ICAL_SYNC_END_DATE}
            CLICKUP_ACCESS_TOKEN: ${CLICKUP_ACCESS_TOKEN}
            CLICKUP_TARGET_LIST_ID: ${CLICKUP_TARGET_LIST_ID}
            CLICKUP_RATE_LIMIT_PER_MIN: ${CLICKUP_RATE_LIMIT_PER_MIN}
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: docsoc
            POSTGRES_PASSWORD: docsoc
            POSTGRES_DB: docsoc
        volumes:
            - docsoc_clickup_postgres_data:/var/lib/postgresql/data

volumes:
    docsoc_clickup_postgres_data:
